import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import profilePic from "../public/images/IMG_0034.jpg";
import Link from "next/link";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    const play = document.querySelector(".fa-circle-play");
    const expand = document.querySelector(".fa-circle-plus");
    const section2 = document.querySelector(`.${styles.section2}`);
    const section1 = document.querySelector(`.${styles.section1}`);
    const section3 = document.querySelector(`.${styles.section3}`);
    const back = section3.querySelector(".fa-arrow-left");
    const iconContainer = section3.querySelectorAll(`.${styles.iconContainer}`);
    const text = section3.querySelectorAll(`.${styles.p}`);
    const nav = document.querySelector(`.${styles.nav}`);
    play.addEventListener("click", () => {
      section1.classList.add(styles.hidden);
      section2.style.opacity = "1";
      section2.style.maxHeight = "100px";
      section2.style.visibility = "visible";
      nav.style.padding = "1.25rem";
    });
    expand.addEventListener("click", () => {
      section1.classList.add(styles.hidden);
      section3.classList.add(styles.show);
      nav.style.width = "18rem";
    });
    section2.addEventListener("click", () => {
      section1.classList.remove(styles.hidden);
      section2.style.opacity = "0";
      section2.style.maxHeight = "0";
      section2.style.visibility = "hidden";
      nav.style.padding = "0 10px";
    });
    back.addEventListener("click", () => {
      section3.classList.remove(styles.show);
      section1.classList.remove(styles.hidden);
    });
  }, []);

  const icon = {
    color: "#00aced",
    fontSize: "35px",
    cursor: "pointer",
  };

  const icon2 = {
    color: "orange",
    fontSize: "35px",
    cursor: "pointer",
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>

      <div className={styles.container}>
        <nav className={styles.nav}>
          <section className={styles.section1}>
            <div className={styles.profileContainer}>
              <Image
                className={styles.img}
                height={35}
                width={35}
                src={profilePic}
              />
              <div>
                <span style={{ fontSize: "10px" }} className={styles.grey}>
                  Hello, I'm
                </span>
                <p className={styles.p}>Richard</p>
              </div>
            </div>
            <div className={styles.iconContainer}>
              <i style={icon2} className="fa-solid fa-circle-play"></i>
              <i style={icon} class="fa-solid fa-circle-plus"></i>
            </div>
          </section>
          <section className={styles.section2}>
            <p className={styles.p}>
              its been{" "}
              <span style={{ color: "white", fontWeight: "bold" }}>
                12 years{" "}
              </span>{" "}
              since i got into web dev. i now have clear principles, the main
              one being{" "}
              <span style={{ color: "white", fontWeight: "bold" }}>
                "value instead of mindless execution"
              </span>
            </p>
          </section>
          <section className={styles.section3}>
            <div className={styles.container1}>
              <div className={styles.iconContainer}>
                <i className={`${styles.icon} fa-solid fa-arrow-left`}></i>
                <p className={styles.p}>Back</p>
              </div>
              <div className={styles.iconContainer}>
                <i className={`${styles.icon} fa-solid fa-user`}></i>
                <Link style={{textDecoration:'none'}} href='/about'><p className={styles.p}>About</p></Link>
              </div>
              <div className={styles.iconContainer}>
                <i className={`${styles.icon} fa-solid fa-code`}></i>
                <Link style={{textDecoration:'none'}} href='/project'><p className={styles.p}>Project</p></Link>
              </div>
              <div className={styles.iconContainer}>
                <i className={`${styles.icon} fa-solid fa-phone`}></i>
                <Link style={{textDecoration:'none'}}  href='/contact'><p className={styles.p}>Contact</p></Link>
              </div>
            </div>
          </section>
        </nav>
      </div>
    </>
  );
}
